#define ALLBITS 0xffffffff

REG(enable, FHARDDOOM_ENABLE, FHARDDOOM_ENABLE_ALL)
/* special: STATUS */
/* special: RESET */
/* special semantics on write */
REG(intr, FHARDDOOM_INTR, FHARDDOOM_INTR_MASK)
REG(intr_enable, FHARDDOOM_INTR_ENABLE, FHARDDOOM_INTR_MASK)

REG(cmd_main_setup, FHARDDOOM_CMD_MAIN_SETUP, FHARDDOOM_CMD_MAIN_SETUP_MASK)
REG(cmd_main_get, FHARDDOOM_CMD_MAIN_GET, FHARDDOOM_CMD_PTR_MASK)
REG(cmd_main_put, FHARDDOOM_CMD_MAIN_PUT, FHARDDOOM_CMD_PTR_MASK)
/* special: CMD_MANUAL_FREE */
/* special: CMD_MANUAL_FEED */
REG(cmd_fence_last, FHARDDOOM_CMD_FENCE_LAST, FHARDDOOM_CMD_FENCE_LAST_MASK)
REG(cmd_fence_wait, FHARDDOOM_CMD_FENCE_WAIT, FHARDDOOM_CMD_FENCE_WAIT_MASK)
REG(cmd_error_code, FHARDDOOM_CMD_ERROR_CODE, FHARDDOOM_CMD_ERROR_CODE_MASK)
REG(cmd_error_data, FHARDDOOM_CMD_ERROR_DATA, ALLBITS)
REG(cmd_info, FHARDDOOM_CMD_INFO, FHARDDOOM_CMD_INFO_MASK)
REG(cmd_header, FHARDDOOM_CMD_HEADER, ALLBITS)
REG(cmd_sub_get, FHARDDOOM_CMD_SUB_GET, FHARDDOOM_CMD_SUB_GET_MASK)
REG(cmd_sub_len, FHARDDOOM_CMD_SUB_LEN, FHARDDOOM_CMD_SUB_LEN_MASK)
REG(cmd_sub_state, FHARDDOOM_CMD_SUB_STATE, FHARDDOOM_CMD_SUB_STATE_MASK)
FIFO(cmd_sub_fifo, FHARDDOOM_CMD_SUB_FIFO)
FIFO_DATA(cmd_sub_fifo, FHARDDOOM_CMD_SUB_FIFO, cmd_sub_fifo_data, FHARDDOOM_CMD_SUB_FIFO_WINDOW, ALLBITS)
REG(cmd_main_state, FHARDDOOM_CMD_MAIN_STATE, FHARDDOOM_CMD_MAIN_STATE_MASK)
FIFO(cmd_main_fifo, FHARDDOOM_CMD_MAIN_FIFO)
FIFO_DATA(cmd_main_fifo, FHARDDOOM_CMD_MAIN_FIFO, cmd_main_fifo_data, FHARDDOOM_CMD_MAIN_FIFO_WINDOW, ALLBITS)

REG(fe_code_addr, FHARDDOOM_FE_CODE_ADDR, FHARDDOOM_FE_CODE_ADDR_MASK)
/* special: FE_CODE_WINDOW */
REG(fe_data_addr, FHARDDOOM_FE_DATA_ADDR, FHARDDOOM_FE_DATA_ADDR_MASK)
/* special: FE_DATA_WINDOW */
REG(fe_pc, FHARDDOOM_FE_PC, FHARDDOOM_FE_PC_MASK)
REG(fe_state, FHARDDOOM_FE_STATE, FHARDDOOM_FE_STATE_MASK)
REG(fe_write_data, FHARDDOOM_FE_WRITE_DATA, ALLBITS)
REG(fe_error_data_a, FHARDDOOM_FE_ERROR_DATA_A, ALLBITS)
REG(fe_error_data_b, FHARDDOOM_FE_ERROR_DATA_B, ALLBITS)
REG(fe_error_code, FHARDDOOM_FE_ERROR_CODE, FHARDDOOM_FE_ERROR_CODE_MASK)
REGS(fe_regs, FHARDDOOM_FE_REG, FHARDDOOM_FE_REG_NUM, ALLBITS)

FIFO(srdcmd, FHARDDOOM_FIFO_SRDCMD)
FIFO_DATA(srdcmd, FHARDDOOM_FIFO_SRDCMD, srdcmd_cmd, FHARDDOOM_FIFO_SRDCMD_CMD_WINDOW, FHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(srdcmd, FHARDDOOM_FIFO_SRDCMD, srdcmd_data, FHARDDOOM_FIFO_SRDCMD_DATA_WINDOW, ALLBITS)
FIFO(spancmd, FHARDDOOM_FIFO_SPANCMD)
FIFO_DATA(spancmd, FHARDDOOM_FIFO_SPANCMD, spancmd_cmd, FHARDDOOM_FIFO_SPANCMD_CMD_WINDOW, FHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(spancmd, FHARDDOOM_FIFO_SPANCMD, spancmd_data, FHARDDOOM_FIFO_SPANCMD_DATA_WINDOW, ALLBITS)
FIFO(colcmd, FHARDDOOM_FIFO_COLCMD)
FIFO_DATA(colcmd, FHARDDOOM_FIFO_COLCMD, colcmd_cmd, FHARDDOOM_FIFO_COLCMD_CMD_WINDOW, FHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(colcmd, FHARDDOOM_FIFO_COLCMD, colcmd_data, FHARDDOOM_FIFO_COLCMD_DATA_WINDOW, ALLBITS)
FIFO(fxcmd, FHARDDOOM_FIFO_FXCMD)
FIFO_DATA(fxcmd, FHARDDOOM_FIFO_FXCMD, fxcmd_cmd, FHARDDOOM_FIFO_FXCMD_CMD_WINDOW, FHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(fxcmd, FHARDDOOM_FIFO_FXCMD, fxcmd_data, FHARDDOOM_FIFO_FXCMD_DATA_WINDOW, ALLBITS)
FIFO(swrcmd, FHARDDOOM_FIFO_SWRCMD)
FIFO_DATA(swrcmd, FHARDDOOM_FIFO_SWRCMD, swrcmd_cmd, FHARDDOOM_FIFO_SWRCMD_CMD_WINDOW, FHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(swrcmd, FHARDDOOM_FIFO_SWRCMD, swrcmd_data, FHARDDOOM_FIFO_SWRCMD_DATA_WINDOW, ALLBITS)
REG(fesem, FHARDDOOM_FIFO_FESEM, FHARDDOOM_FIFO_SEM_MASK)
REG(srdsem, FHARDDOOM_FIFO_SRDSEM, FHARDDOOM_FIFO_SEM_MASK)
REG(colsem, FHARDDOOM_FIFO_COLSEM, FHARDDOOM_FIFO_SEM_MASK)
REG(spansem, FHARDDOOM_FIFO_SPANSEM, FHARDDOOM_FIFO_SEM_MASK)
FIFO(colin, FHARDDOOM_FIFO_COLIN)
FIFO(fxin, FHARDDOOM_FIFO_FXIN)
FIFO_DATA_BLOCK(colin, FHARDDOOM_FIFO_COLIN, colin_data, FHARDDOOM_FIFO_COLIN_DATA_WINDOW)
FIFO_DATA_BLOCK(fxin, FHARDDOOM_FIFO_FXIN, fxin_data, FHARDDOOM_FIFO_FXIN_DATA_WINDOW)
FIFO(spanout, FHARDDOOM_FIFO_SPANOUT)
FIFO(colout, FHARDDOOM_FIFO_COLOUT)
FIFO(fxout, FHARDDOOM_FIFO_FXOUT)
FIFO_DATA_BLOCK(spanout, FHARDDOOM_FIFO_SPANOUT, spanout_data, FHARDDOOM_FIFO_SPANOUT_DATA_WINDOW)
FIFO_DATA_BLOCK(colout, FHARDDOOM_FIFO_COLOUT, colout_data, FHARDDOOM_FIFO_COLOUT_DATA_WINDOW)
FIFO_DATA_BLOCK(fxout, FHARDDOOM_FIFO_FXOUT, fxout_data, FHARDDOOM_FIFO_FXOUT_DATA_WINDOW)
FIFO_DATA64(colout, FHARDDOOM_FIFO_COLOUT, colout_mask, FHARDDOOM_FIFO_COLOUT_MASK_WINDOW)
FIFO_DATA64(fxout, FHARDDOOM_FIFO_FXOUT, fxout_mask, FHARDDOOM_FIFO_FXOUT_MASK_WINDOW)

REGS(mmu_slot, FHARDDOOM_MMU_SLOT, FHARDDOOM_MMU_SLOT_NUM, FHARDDOOM_MMU_SLOT_MASK)
REGS(mmu_client_tlb_tag, FHARDDOOM_MMU_CLIENT_TLB_TAG, FHARDDOOM_MMU_CLIENT_NUM, FHARDDOOM_MMU_TLB_TAG_MASK)
REGS(mmu_client_tlb_value, FHARDDOOM_MMU_CLIENT_TLB_VALUE, FHARDDOOM_MMU_CLIENT_NUM, FHARDDOOM_PTE_MASK)
REGS(mmu_client_va, FHARDDOOM_MMU_CLIENT_VA, FHARDDOOM_MMU_CLIENT_NUM, FHARDDOOM_VA_MASK)
REGS(mmu_tlb_tag, FHARDDOOM_MMU_TLB_TAG, FHARDDOOM_MMU_TLB_SIZE, FHARDDOOM_MMU_TLB_TAG_MASK)
REGS(mmu_tlb_value, FHARDDOOM_MMU_TLB_VALUE, FHARDDOOM_MMU_TLB_SIZE, FHARDDOOM_PTE_MASK)

REGS(stats, FHARDDOOM_STATS, FHARDDOOM_STATS_NUM, ALLBITS)

REG(swr_state, FHARDDOOM_SWR_STATE, FHARDDOOM_SWR_STATE_MASK)
REG(swr_transmap_va, FHARDDOOM_SWR_TRANSMAP_VA, FHARDDOOM_SWR_TRANSMAP_VA_MASK)
REG(swr_dst_va, FHARDDOOM_SWR_DST_VA, FHARDDOOM_BLOCK_VA_MASK)
REG(swr_dst_pitch, FHARDDOOM_SWR_DST_PITCH, FHARDDOOM_BLOCK_PITCH_MASK)
REG64(swr_block_mask, FHARDDOOM_SWR_BLOCK_MASK)
REGS8(swr_src_buf, FHARDDOOM_SWR_SRC_BUF, FHARDDOOM_BLOCK_SIZE)
REGS8(swr_dst_buf, FHARDDOOM_SWR_DST_BUF, FHARDDOOM_BLOCK_SIZE)
REGS8(swr_trans_buf, FHARDDOOM_SWR_TRANS_BUF, FHARDDOOM_BLOCK_SIZE)

REG(srd_state, FHARDDOOM_SRD_STATE, FHARDDOOM_SRD_STATE_MASK)
REG(srd_src_va, FHARDDOOM_SRD_SRC_VA, FHARDDOOM_BLOCK_VA_MASK)
REG(srd_src_pitch, FHARDDOOM_SRD_SRC_PITCH, FHARDDOOM_BLOCK_PITCH_MASK)

REG(span_state, FHARDDOOM_SPAN_STATE, FHARDDOOM_SPAN_STATE_MASK)
REG(span_src, FHARDDOOM_SPAN_SRC, FHARDDOOM_SPAN_SRC_MASK)
REG(span_uvmask, FHARDDOOM_SPAN_UVMASK, FHARDDOOM_SPAN_UVMASK_MASK)
REG(span_ustart, FHARDDOOM_SPAN_USTART, ALLBITS)
REG(span_vstart, FHARDDOOM_SPAN_VSTART, ALLBITS)
REG(span_ustep, FHARDDOOM_SPAN_USTEP, ALLBITS)
REG(span_vstep, FHARDDOOM_SPAN_VSTEP, ALLBITS)

REG(fx_state, FHARDDOOM_FX_STATE, FHARDDOOM_FX_STATE_MASK)
REG(fx_skip, FHARDDOOM_FX_SKIP, FHARDDOOM_FX_SKIP_MASK)
REGS(fx_col, FHARDDOOM_FX_COL, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_FX_COL_MASK)
REGS8(fx_buf, FHARDDOOM_FX_BUF, FHARDDOOM_FX_BUF_SIZE)
REGS8(fx_cmap_a, FHARDDOOM_FX_CMAP_A, FHARDDOOM_COLORMAP_SIZE)
REGS8(fx_cmap_b, FHARDDOOM_FX_CMAP_B, FHARDDOOM_COLORMAP_SIZE)

REG(col_state, FHARDDOOM_COL_STATE, FHARDDOOM_COL_STATE_MASK)
REG(col_stage_cmap_b_va, FHARDDOOM_COL_STAGE_CMAP_B_VA, FHARDDOOM_COL_COLS_CMAP_B_VA_MASK)
REG(col_stage_src_va, FHARDDOOM_COL_STAGE_SRC_VA, FHARDDOOM_VA_MASK)
REG(col_stage_src_pitch, FHARDDOOM_COL_STAGE_SRC_PITCH, FHARDDOOM_COL_COLS_SRC_PITCH_MASK)
REG(col_stage_ustart, FHARDDOOM_COL_STAGE_USTART, ALLBITS)
REG(col_stage_ustep, FHARDDOOM_COL_STAGE_USTEP, ALLBITS)
REGS(col_cols_cmap_b_va, FHARDDOOM_COL_COLS_CMAP_B_VA, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_COL_COLS_CMAP_B_VA_MASK)
REGS(col_cols_src_va, FHARDDOOM_COL_COLS_SRC_VA, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_VA_MASK)
REGS(col_cols_src_pitch, FHARDDOOM_COL_COLS_SRC_PITCH, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_COL_COLS_SRC_PITCH_MASK)
REGS(col_cols_ustart, FHARDDOOM_COL_COLS_USTART, FHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_ustep, FHARDDOOM_COL_COLS_USTEP, FHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_src_height, FHARDDOOM_COL_COLS_SRC_HEIGHT, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_COL_COLS_SRC_HEIGHT_MASK)
REGS(col_cols_state, FHARDDOOM_COL_COLS_STATE, FHARDDOOM_BLOCK_SIZE, FHARDDOOM_COL_COLS_STATE_MASK)
REGS8(col_cmap_a, FHARDDOOM_COL_CMAP_A, FHARDDOOM_COLORMAP_SIZE)
REGS8(col_data, FHARDDOOM_COL_DATA, FHARDDOOM_COL_DATA_SIZE * FHARDDOOM_BLOCK_SIZE)

REGS(cache_tag, FHARDDOOM_CACHE_TAG, FHARDDOOM_CACHE_CLIENT_NUM * FHARDDOOM_CACHE_SIZE, FHARDDOOM_CACHE_TAG_MASK)
REGS8(cache_data, FHARDDOOM_CACHE_DATA, FHARDDOOM_CACHE_CLIENT_NUM * FHARDDOOM_CACHE_SIZE * FHARDDOOM_BLOCK_SIZE)

#undef REG
#undef REG64
#undef REGS
#undef REGS8
#undef FIFO
#undef FIFO_DATA
#undef FIFO_DATA64
#undef FIFO_DATA_BLOCK
#undef ALLBITS
