#define ALLBITS 0xffffffff

REG(enable, UHARDDOOM_ENABLE, UHARDDOOM_ENABLE_ALL)
/* special: STATUS */
/* special: RESET */
/* special semantics on write */
REG(intr, UHARDDOOM_INTR, UHARDDOOM_INTR_MASK)
REG(intr_enable, UHARDDOOM_INTR_ENABLE, UHARDDOOM_INTR_MASK)

/* special semantics on write */
REG(batch_pdp, UHARDDOOM_BATCH_PDP, UHARDDOOM_PDP_MASK)
REG(batch_get, UHARDDOOM_BATCH_GET, UHARDDOOM_BATCH_PTR_MASK)
REG(batch_put, UHARDDOOM_BATCH_PUT, UHARDDOOM_BATCH_PTR_MASK)
REG(batch_wait, UHARDDOOM_BATCH_WAIT, UHARDDOOM_BATCH_PTR_MASK)
REG(batch_wrap_from, UHARDDOOM_BATCH_WRAP_FROM, UHARDDOOM_BATCH_PTR_MASK)
REG(batch_wrap_to, UHARDDOOM_BATCH_WRAP_TO, UHARDDOOM_BATCH_PTR_MASK)

REG(job_pdp, UHARDDOOM_JOB_PDP, UHARDDOOM_PDP_MASK)
REG(job_cmd_ptr, UHARDDOOM_JOB_CMD_PTR, UHARDDOOM_CMD_PTR_MASK)
REG(job_cmd_size, UHARDDOOM_JOB_CMD_SIZE, UHARDDOOM_CMD_SIZE_MASK)
/* special: JOB_TRIGGER */
REG(job_state, UHARDDOOM_JOB_STATE, UHARDDOOM_JOB_STATE_MASK)

REG(cmd_fe_ptr, UHARDDOOM_CMD_FE_PTR, UHARDDOOM_CMD_PTR_MASK)
REG(cmd_read_ptr, UHARDDOOM_CMD_READ_PTR, UHARDDOOM_CMD_PTR_MASK)
REG(cmd_read_size, UHARDDOOM_CMD_READ_SIZE, UHARDDOOM_CMD_SIZE_MASK)
FIFO(cmd_fifo, UHARDDOOM_CMD_FIFO)
FIFO_DATA(cmd_fifo, UHARDDOOM_CMD_FIFO, cmd_fifo_data, UHARDDOOM_CMD_FIFO_WINDOW, ALLBITS)

REG(fe_code_addr, UHARDDOOM_FE_CODE_ADDR, UHARDDOOM_FE_CODE_ADDR_MASK)
/* special: FE_CODE_WINDOW */
REG(fe_data_addr, UHARDDOOM_FE_DATA_ADDR, UHARDDOOM_FE_DATA_ADDR_MASK)
/* special: FE_DATA_WINDOW */
REG(fe_pc, UHARDDOOM_FE_PC, UHARDDOOM_FE_PC_MASK)
REG(fe_state, UHARDDOOM_FE_STATE, UHARDDOOM_FE_STATE_MASK)
REG(fe_write_data, UHARDDOOM_FE_WRITE_DATA, ALLBITS)
REG(fe_error_data_a, UHARDDOOM_FE_ERROR_DATA_A, ALLBITS)
REG(fe_error_data_b, UHARDDOOM_FE_ERROR_DATA_B, ALLBITS)
REG(fe_error_code, UHARDDOOM_FE_ERROR_CODE, UHARDDOOM_FE_ERROR_CODE_MASK)
REGS(fe_regs, UHARDDOOM_FE_REG, UHARDDOOM_FE_REG_NUM, ALLBITS)

FIFO(srdcmd, UHARDDOOM_FIFO_SRDCMD)
FIFO_DATA(srdcmd, UHARDDOOM_FIFO_SRDCMD, srdcmd_cmd, UHARDDOOM_FIFO_SRDCMD_CMD_WINDOW, UHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(srdcmd, UHARDDOOM_FIFO_SRDCMD, srdcmd_data, UHARDDOOM_FIFO_SRDCMD_DATA_WINDOW, ALLBITS)
FIFO(spancmd, UHARDDOOM_FIFO_SPANCMD)
FIFO_DATA(spancmd, UHARDDOOM_FIFO_SPANCMD, spancmd_cmd, UHARDDOOM_FIFO_SPANCMD_CMD_WINDOW, UHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(spancmd, UHARDDOOM_FIFO_SPANCMD, spancmd_data, UHARDDOOM_FIFO_SPANCMD_DATA_WINDOW, ALLBITS)
FIFO(colcmd, UHARDDOOM_FIFO_COLCMD)
FIFO_DATA(colcmd, UHARDDOOM_FIFO_COLCMD, colcmd_cmd, UHARDDOOM_FIFO_COLCMD_CMD_WINDOW, UHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(colcmd, UHARDDOOM_FIFO_COLCMD, colcmd_data, UHARDDOOM_FIFO_COLCMD_DATA_WINDOW, ALLBITS)
FIFO(fxcmd, UHARDDOOM_FIFO_FXCMD)
FIFO_DATA(fxcmd, UHARDDOOM_FIFO_FXCMD, fxcmd_cmd, UHARDDOOM_FIFO_FXCMD_CMD_WINDOW, UHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(fxcmd, UHARDDOOM_FIFO_FXCMD, fxcmd_data, UHARDDOOM_FIFO_FXCMD_DATA_WINDOW, ALLBITS)
FIFO(swrcmd, UHARDDOOM_FIFO_SWRCMD)
FIFO_DATA(swrcmd, UHARDDOOM_FIFO_SWRCMD, swrcmd_cmd, UHARDDOOM_FIFO_SWRCMD_CMD_WINDOW, UHARDDOOM_FIFO_CMD_MASK)
FIFO_DATA(swrcmd, UHARDDOOM_FIFO_SWRCMD, swrcmd_data, UHARDDOOM_FIFO_SWRCMD_DATA_WINDOW, ALLBITS)
REG(fesem, UHARDDOOM_FIFO_FESEM, UHARDDOOM_FIFO_SEM_MASK)
REG(srdsem, UHARDDOOM_FIFO_SRDSEM, UHARDDOOM_FIFO_SEM_MASK)
REG(colsem, UHARDDOOM_FIFO_COLSEM, UHARDDOOM_FIFO_SEM_MASK)
REG(spansem, UHARDDOOM_FIFO_SPANSEM, UHARDDOOM_FIFO_SEM_MASK)
FIFO(colin, UHARDDOOM_FIFO_COLIN)
FIFO(fxin, UHARDDOOM_FIFO_FXIN)
FIFO_DATA_BLOCK(colin, UHARDDOOM_FIFO_COLIN, colin_data, UHARDDOOM_FIFO_COLIN_DATA_WINDOW)
FIFO_DATA_BLOCK(fxin, UHARDDOOM_FIFO_FXIN, fxin_data, UHARDDOOM_FIFO_FXIN_DATA_WINDOW)
FIFO(spanout, UHARDDOOM_FIFO_SPANOUT)
FIFO(colout, UHARDDOOM_FIFO_COLOUT)
FIFO(fxout, UHARDDOOM_FIFO_FXOUT)
FIFO_DATA_BLOCK(spanout, UHARDDOOM_FIFO_SPANOUT, spanout_data, UHARDDOOM_FIFO_SPANOUT_DATA_WINDOW)
FIFO_DATA_BLOCK(colout, UHARDDOOM_FIFO_COLOUT, colout_data, UHARDDOOM_FIFO_COLOUT_DATA_WINDOW)
FIFO_DATA_BLOCK(fxout, UHARDDOOM_FIFO_FXOUT, fxout_data, UHARDDOOM_FIFO_FXOUT_DATA_WINDOW)
FIFO_DATA64(colout, UHARDDOOM_FIFO_COLOUT, colout_mask, UHARDDOOM_FIFO_COLOUT_MASK_WINDOW)
FIFO_DATA64(fxout, UHARDDOOM_FIFO_FXOUT, fxout_mask, UHARDDOOM_FIFO_FXOUT_MASK_WINDOW)

REG(tlb_kernel_pdp, UHARDDOOM_TLB_KERNEL_PDP, UHARDDOOM_PDP_MASK)
REG(tlb_user_pdp, UHARDDOOM_TLB_USER_PDP, UHARDDOOM_PDP_MASK)
REGS(tlb_pool_pde_tag, UHARDDOOM_TLB_POOL_PDE_TAG, UHARDDOOM_TLB_POOL_PDE_SIZE, UHARDDOOM_TLB_TAG_MASK_PD)
REGS(tlb_pool_pde_value, UHARDDOOM_TLB_POOL_PDE_VALUE, UHARDDOOM_TLB_POOL_PDE_SIZE, UHARDDOOM_PDE_MASK)
REGS(tlb_client_pte_tag, UHARDDOOM_TLB_CLIENT_PTE_TAG, UHARDDOOM_TLB_CLIENT_NUM, UHARDDOOM_TLB_TAG_MASK_PT)
REGS(tlb_client_pte_value, UHARDDOOM_TLB_CLIENT_PTE_VALUE, UHARDDOOM_TLB_CLIENT_NUM, UHARDDOOM_PTE_MASK)
REGS(tlb_client_va, UHARDDOOM_TLB_CLIENT_VA, UHARDDOOM_TLB_CLIENT_NUM, ALLBITS)
REGS(tlb_pool_pte_tag, UHARDDOOM_TLB_POOL_PTE_TAG, UHARDDOOM_TLB_POOL_PTE_SIZE, UHARDDOOM_TLB_TAG_MASK_PT)
REGS(tlb_pool_pte_value, UHARDDOOM_TLB_POOL_PTE_VALUE, UHARDDOOM_TLB_POOL_PTE_SIZE, UHARDDOOM_PTE_MASK)

/* XXX: STATS */

REG(srd_state, UHARDDOOM_SRD_STATE, UHARDDOOM_SRD_STATE_MASK)
REG(srd_src_ptr, UHARDDOOM_SRD_SRC_PTR, UHARDDOOM_BLOCK_PTR_MASK)
REG(srd_src_pitch, UHARDDOOM_SRD_SRC_PITCH, UHARDDOOM_BLOCK_PITCH_MASK)

REG(span_state, UHARDDOOM_SPAN_STATE, UHARDDOOM_SPAN_STATE_MASK)
REG(span_src_ptr, UHARDDOOM_SPAN_SRC_PTR, ALLBITS)
REG(span_src_pitch, UHARDDOOM_SPAN_SRC_PITCH, ALLBITS)
REG(span_uvmask, UHARDDOOM_SPAN_UVMASK, UHARDDOOM_SPAN_UVMASK_MASK)
REG(span_ustart, UHARDDOOM_SPAN_USTART, ALLBITS)
REG(span_vstart, UHARDDOOM_SPAN_VSTART, ALLBITS)
REG(span_ustep, UHARDDOOM_SPAN_USTEP, ALLBITS)
REG(span_vstep, UHARDDOOM_SPAN_VSTEP, ALLBITS)

REG(swr_state, UHARDDOOM_SWR_STATE, UHARDDOOM_SWR_STATE_MASK)
REG(swr_transmap_ptr, UHARDDOOM_SWR_TRANSMAP_PTR, ALLBITS)
REG(swr_dst_ptr, UHARDDOOM_SWR_DST_PTR, UHARDDOOM_BLOCK_PTR_MASK)
REG(swr_dst_pitch, UHARDDOOM_SWR_DST_PITCH, UHARDDOOM_BLOCK_PITCH_MASK)
REG64(swr_block_mask, UHARDDOOM_SWR_BLOCK_MASK)
REGS8(swr_src_buf, UHARDDOOM_SWR_SRC_BUF, UHARDDOOM_BLOCK_SIZE)
REGS8(swr_dst_buf, UHARDDOOM_SWR_DST_BUF, UHARDDOOM_BLOCK_SIZE)
REGS8(swr_trans_buf, UHARDDOOM_SWR_TRANS_BUF, UHARDDOOM_BLOCK_SIZE)

REG(fx_state, UHARDDOOM_FX_STATE, UHARDDOOM_FX_STATE_MASK)
REG(fx_skip, UHARDDOOM_FX_SKIP, UHARDDOOM_FX_SKIP_MASK)
REGS(fx_col, UHARDDOOM_FX_COL, UHARDDOOM_BLOCK_SIZE, UHARDDOOM_FX_COL_MASK)
REGS8(fx_buf, UHARDDOOM_FX_BUF, UHARDDOOM_FX_BUF_SIZE)
REGS8(fx_cmap, UHARDDOOM_FX_CMAP, UHARDDOOM_COLORMAP_SIZE)

REG(col_state, UHARDDOOM_COL_STATE, UHARDDOOM_COL_STATE_MASK)
REG(col_stage_cmap_b_ptr, UHARDDOOM_COL_STAGE_CMAP_B_PTR, ALLBITS)
REG(col_stage_src_ptr, UHARDDOOM_COL_STAGE_SRC_PTR, ALLBITS)
REG(col_stage_src_pitch, UHARDDOOM_COL_STAGE_SRC_PITCH, ALLBITS)
REG(col_stage_ustart, UHARDDOOM_COL_STAGE_USTART, ALLBITS)
REG(col_stage_ustep, UHARDDOOM_COL_STAGE_USTEP, ALLBITS)
REGS(col_cols_cmap_b_ptr, UHARDDOOM_COL_COLS_CMAP_B_PTR, UHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_src_ptr, UHARDDOOM_COL_COLS_SRC_PTR, UHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_src_pitch, UHARDDOOM_COL_COLS_SRC_PITCH, UHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_ustart, UHARDDOOM_COL_COLS_USTART, UHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_ustep, UHARDDOOM_COL_COLS_USTEP, UHARDDOOM_BLOCK_SIZE, ALLBITS)
REGS(col_cols_src_height, UHARDDOOM_COL_COLS_SRC_HEIGHT, UHARDDOOM_BLOCK_SIZE, UHARDDOOM_COL_COLS_SRC_HEIGHT_MASK)
REGS(col_cols_state, UHARDDOOM_COL_COLS_STATE, UHARDDOOM_BLOCK_SIZE, UHARDDOOM_COL_COLS_STATE_MASK)
REGS8(col_cmap_a, UHARDDOOM_COL_CMAP_A, UHARDDOOM_COLORMAP_SIZE)
REGS8(col_data, UHARDDOOM_COL_DATA, UHARDDOOM_COL_DATA_SIZE * UHARDDOOM_BLOCK_SIZE)

REGS(cache_tag, UHARDDOOM_CACHE_TAG, UHARDDOOM_CACHE_CLIENT_NUM * UHARDDOOM_CACHE_SIZE, UHARDDOOM_CACHE_TAG_MASK)
REGS8(cache_data, UHARDDOOM_CACHE_DATA, UHARDDOOM_CACHE_CLIENT_NUM * UHARDDOOM_CACHE_SIZE * UHARDDOOM_BLOCK_SIZE)

#undef REG
#undef REG64
#undef REGS
#undef REGS8
#undef FIFO
#undef FIFO_DATA
#undef FIFO_DATA64
#undef FIFO_DATA_BLOCK
#undef ALLBITS
